name: build image and push on docker hub
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3


      - name: Generate tags
        id: docker_tags
        uses: anothrNick/github-tag-action@1.40.0
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         WITH_V: true
         
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5.8
        with:
          image: 7011347758/test
          tags: ${{ steps.docker_tags.outputs.tag }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


